"""empty message

Revision ID: 7951c5a38a4c
Revises: 68afb41ca0cf
Create Date: 2025-12-31 22:46:00.737176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7951c5a38a4c'
down_revision: Union[str, Sequence[str], None] = '68afb41ca0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'playlist_id', name='uq_playlist_likes_user_playlist')
    )
    op.create_index(op.f('ix_playlist_likes_id'), 'playlist_likes', ['id'], unique=False)
    op.create_index(op.f('ix_playlist_likes_playlist_id'), 'playlist_likes', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_likes_user_id'), 'playlist_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_likes_user_id'), table_name='playlist_likes')
    op.drop_index(op.f('ix_playlist_likes_playlist_id'), table_name='playlist_likes')
    op.drop_index(op.f('ix_playlist_likes_id'), table_name='playlist_likes')
    op.drop_table('playlist_likes')
    # ### end Alembic commands ###
